# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 455c43f33c17fb906f3472937851122dc4142d9f9566341722f19b934af23c8a384d9a7df8ee3f6b09484f04bda10c922294d9aaacfb34540fd1f1512cb2ecbd

test:
  secret_key_base: b0f4374f7340cfd4babd7dbcb999cec9f4e4898eac3e43e6f641511e21c1da8b9d9628696cdc663d75836b32581f8bcc1400ecdc9649b865d9abf809b3ae6c8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
